version: '3.8'

services:
  discord-bot:
    build: .
    container_name: evil-discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
